In [1]:
import torch
from torch import Tensor
from torch.autograd import Variable
from torch.nn.functional import relu, max_pool2d
from torch.nn import Conv2d, Linear, MSELoss

In [2]:
# apply relu
# relu(input, inplace = False)
x = Variable(Tensor(2,5).normal_())
print (x)
y = relu(x)
print(y)

tensor([[ 0.0312,  1.1382,  1.3751,  1.3059,  1.3983],
        [-1.9474, -0.8050, -0.0096,  1.0111, -0.5008]])
tensor([[ 0.0312,  1.1382,  1.3751,  1.3059,  1.3983],
        [ 0.0000,  0.0000,  0.0000,  1.0111,  0.0000]])


In [3]:
# get N x C x H x W input
# return N x C x floor(H/h) x floor(W/w)
x = Variable(Tensor(1,2,3,6).random_(5))
print (x)
max_pool2d(x, (1,2))


tensor([[[[ 0.,  4.,  3.,  3.,  4.,  1.],
          [ 0.,  0.,  4.,  2.,  4.,  3.],
          [ 4.,  3.,  2.,  1.,  3.,  4.]],

         [[ 0.,  4.,  4.,  1.,  0.,  1.],
          [ 2.,  1.,  1.,  1.,  3.,  2.],
          [ 3.,  2.,  2.,  1.,  3.,  2.]]]])


tensor([[[[ 4.,  3.,  4.],
          [ 0.,  4.,  4.],
          [ 4.,  2.,  4.]],

         [[ 4.,  4.,  1.],
          [ 2.,  1.,  3.],
          [ 3.,  2.,  3.]]]])

In [4]:
# Linear
# input NxC -> NxD

# weight and bias are randomized
f = Linear(in_features = 10, out_features = 4)
f.weight.size()
f.bias.size()
x = Variable(Tensor(52, 10).normal_())
y = f(x)
y.size()

torch.Size([52, 4])

In [5]:
# convolutional layer
# input: N x C x H x W
# output: N x D x (H-h+1) x (W-w+1)

l = Conv2d(in_channels = 4, out_channels = 5, kernel_size = (2,3))
l.weight.size()
l.bias.size()
x = Variable(Tensor(62, 4, 10, 3).normal_())
y = l(x)
y.size()

torch.Size([62, 5, 9, 1])

In [14]:
# MSELoss: mean squared error loss
# sum / total number of components

f = MSELoss()
x = Variable(Tensor(2,2).random_(5))
y = Variable(Tensor(2,2).random_(10))
print (x, '\n',y)
f(x,y)

tensor([[ 2.,  0.],
        [ 1.,  3.]]) 
 tensor([[ 5.,  3.],
        [ 5.,  4.]])


tensor(8.7500)